export const WHEEL_TYPE = "WHEEL_TYPE";
export const FUEL_TYPE = "FUEL_TYPE";
export const PRICE = "PRICE";
export const PRODUCTION_YEAR = "PRODUCTION_YEAR";
export const ENGINE_CAPACITY = " ENGINE_CAPACITY";
export const BATTERY_CAPACITY = "BATTERY_CAPACITY";
export const ORIGIN_COUNTRY = "ORIGIN_COUNTRY";
export const FULL_WEIGHT = "FULL_WEIGHT";